### ISSUE TITLE
How to determine if asset is an NFT

### ISSUE THREAD

**Issue by stein-f** [RandGallery/creator-tools#1]
Hey Chris. Thanks for this and the arc69 repos - they have been super useful.

I was hoping you could help answer a question:

"What rules are you applying to determine whether an asset is an NFT"

I see in list.js you have

```
amount >= 1
```

but I imagine for rand gallery you have something more complex. I am assuming there is no standardized to determine this, but you make a guess based on some assumptions

Many thanks

**Comment by ChrisAntaki** [comment]
Hey @algo-stein ! I'm glad the repos have helped you out. The tools in this repository assume a creator (1) _knows_ they created NFTs in a certain wallet and (2) wants to do things with them
